name: unit-tests

on:
  push:

jobs:
  test:
    environment: Automation test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout from PR branch
        uses: actions/checkout@v4

      - name: Set Node.js 20.x for GitHub Action
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: installing node_modules
        run: npm install

      - name: run tests
        run: npm run test

